[physics.biped]
mass = 1.0

[object.tree]
model = "maps/tree.gltf"
colour = [0.0, 1.0, 0.0]

[object.crate]
physics = "biped"
model = "maps/cube.gltf"
colour = [0.0, 0.0, 1.0]

[object.player]
physics = "biped"
model = "maps/cube.gltf"
colour = [1.0, 0.0, 0.0]

[globals]
gravity_scale = 1.0
player_object = "player"
player_accel = 0.01
player_drag_scale = 0.2

[scenario]
player_location = {pos = [0.0, 0.0, 0.0]}

[[scenario.scenery]]
object_type = "tree"
position = {pos = [20.0, 0.0, 0.0]}

[[scenario.scenery]]
object_type = "tree"
position = {pos = [15.0, 0.0, 0.0]}

[[scenario.scenery]]
object_type = "crate"
position = {pos = [10.0, 0.0, 0.0]}

[[scenario.scenery]]
object_type = "crate"
position = {pos = [5.0, 0.0, 0.0]}

[[scenario.scenery]]
object_type = "crate"
position = {pos = [0.0, 15.0, 0.0]}

[[scenario.scenery]]
object_type = "crate"
position = {pos = [0.0, 0.0, 5.0]}

[[scenario.scenery]]
object_type = "crate"
position = {pos = [0.0, 0.0, 10.0]}